language: cpp
compiler:
  - clang
  - gcc
before_install:
 - sudo apt-get update -qq -y
 - sudo apt-get install libboost1.48-dev -y
env:
  global:
    - BOOST_INCLUDES=/usr/include
    - BOOST_LIBS=/usr/libs
script: scons && scons test
branches:
  only:
    - experimental
notifications:
  recipients:
    - travis@zaphoyd.com
  email:
    on_success: change
    on_failure: always